package Acme::CPANLists::Import::BKB::CheckMemory;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/memory-check-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"Devel::GDB"},{module=>"Devel::Leak"},{module=>"Devel::LeakTrace"},{module=>"Devel::LeakTrace::Fast"},{module=>"Devel::MAT"},{module=>"Devel::Plumber"},{module=>"Devel::Valgrind::Client"},{module=>"Test::LeakTrace"},{module=>"Test::MemoryGrowth"},{module=>"Test::NoLeaks"},{module=>"Test::RunValgrind"},{module=>"Test::Valgrind"}],summary=>"Perl modules for checking memory (2017)"});

1;
# ABSTRACT: Perl modules for checking memory (2017)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/memory-check-modules/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

