package Acme::CPANLists::Import::BKB::FastCGI;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/fastcgi-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"AnyEvent::FCGI"},{module=>"CGI::Application::FastCGI"},{module=>"CGI::Fast"},{module=>"FCGI"},{module=>"FCGI::Async"},{module=>"FCGI::Client"},{module=>"FCGI::EV"},{module=>"Mojo::Server::FastCGI"},{module=>"Net::FastCGI"},{module=>"POE::Component::FastCGI"},{module=>"Plack::Handler::FCGI"}],summary=>"FastCGI Perl modules (2016)"});

1;
# ABSTRACT: FastCGI Perl modules (2016)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/fastcgi-modules/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

