package Acme::CPANLists::Import::BKB::FindDependencies;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/perl-dependencies/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"Devel::Loaded"},{module=>"Module::Extract::Use"},{module=>"Module::ExtractUse"},{module=>"Module::Info"},{module=>"Module::Metadata"},{module=>"Module::ScanDeps"},{module=>"Module::Used"}],summary=>"Modules for finding Perl dependencies (2017)"});

1;
# ABSTRACT: Modules for finding Perl dependencies (2017)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/perl-dependencies/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

