package Acme::CPANLists::Import::BKB::Handy;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/handy-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"App::cpanminus"},{module=>"CGI"},{module=>"Carp"},{module=>"DBD::SQLite"},{module=>"DBD::mysql"},{module=>"DBI"},{module=>"ExtUtils::MakeMaker"},{module=>"File::Copy"},{module=>"File::Find"},{module=>"File::Spec"},{module=>"File::Temp"},{module=>"FindBin"},{module=>"Module::Build"},{module=>"Template"},{module=>"Test"},{module=>"Test::More"},{module=>"Test::Simple"}],summary=>"Handy Perl modules (2011)"});

1;
# ABSTRACT: Handy Perl modules (2011)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/handy-modules/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

