package Acme::CPANLists::Import::BKB::Japanese;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/cpan-japanese-language/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"DateTime::Calendar::Japanese::Era"},{module=>"Lingua::JA::FindDates"},{module=>"Lingua::JA::Moji"},{module=>"Lingua::JA::Numbers"},{module=>"Lingua::JA::Yomi"},{module=>"Text::MeCab"}],summary=>"CPAN modules for dealing with the Japanese language (2012)"});

1;
# ABSTRACT: CPAN modules for dealing with the Japanese language (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/cpan-japanese-language/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

