package Acme::CPANLists::Import::BKB::RemoveHTMLTags;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [https://www.lemoda.net/perl/html-cleanup-modules/index.html] (retrieved on 2017-03-27). Visit the URL for the full contents.",entries=>[{module=>"HTML::Defang"},{module=>"HTML::Detoxifier"},{module=>"HTML::Laundry"},{module=>"HTML::Restrict"},{module=>"HTML::Scrubber"},{module=>"HTML::Strip"},{module=>"HTML::TagFilter"},{module=>"HTML::Truncate"},{module=>"MojoMojo::Declaw"}],summary=>"Perl modules to remove HTML tags (2017)"});

1;
# ABSTRACT: Perl modules to remove HTML tags (2017)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<https://www.lemoda.net/perl/html-cleanup-modules/index.html> (retrieved on 2017-03-27). Visit the URL for the full contents.

